const emp_cf_01_types = require('../models/emp_cf_01_types.js')
const emp_cf_02_classes = require('../models/emp_cf_02_class.js')
const emp_cf_03_employtypes = require('../models/emp_cf_03_employtypes.js')
const emp_cf_04_statuses = require('../models/emp_cf_04_statuses.js')
const emp_cf_cb_maritals = require('../models/emp_cf_cb_maritals.js')
const emp_cf_per_job_leavetype = require('../models/emp_cf_per_job_leavetype.js')
const emp_cf_per_job_workday = require('../models/emp_cf_per_job_workday.js')
const emp_cf_plan_a_workgroup = require('../models/emp_cf_plan_a_workgroup.js')
const emp_cf_plan_b_function = require('../models/emp_cf_plan_b_function.js')
const emp_cf_plan_c_level = require('../models/emp_cf_plan_c_level.js')
const emp_cf_plan_d_grade = require('../models/emp_cf_plan_d_grade.js')
const emp_cf_plan_posttitle = require('../models/emp_cf_plan_posttitle.js')
const emp_cf_rec_01_education = require('../models/emp_cf_rec_01_education.js')
const emp_cf_rec_02_fieldstudy = require('../models/emp_cf_rec_02_fieldstudy.js')
const emp_cf_rec_03_yearexp = require('../models/emp_cf_rec_03_yearexp.js')
const emp_cf_rec_04_age = require('../models/emp_cf_rec_04_age.js')
const emp_cf_rec_05_english = require('../models/emp_cf_rec_05_english.js')

const CFHRInit = (connection) =>{
    emp_cf_01_types.init(connection)
    emp_cf_02_classes.init(connection)
    emp_cf_03_employtypes.init(connection)
    emp_cf_04_statuses.init(connection)
    emp_cf_cb_maritals.init(connection)
    emp_cf_per_job_leavetype.init(connection)
    emp_cf_per_job_workday.init(connection)
    emp_cf_plan_a_workgroup.init(connection)
    emp_cf_plan_b_function.init(connection)
    emp_cf_plan_c_level.init(connection)
    emp_cf_plan_d_grade.init(connection)
    emp_cf_plan_posttitle.init(connection)
    emp_cf_rec_01_education.init(connection)
    emp_cf_rec_02_fieldstudy.init(connection)
    emp_cf_rec_03_yearexp.init(connection)
    emp_cf_rec_04_age.init(connection)
    emp_cf_rec_05_english.init(connection)
}

const CFHRAssociate = (models)=>{
    emp_cf_01_types.associate(models)
    emp_cf_02_classes.associate(models)
    emp_cf_03_employtypes.associate(models)
    emp_cf_04_statuses.associate(models)
    emp_cf_cb_maritals.associate(models)
    emp_cf_per_job_leavetype.associate(models)
    emp_cf_per_job_workday.associate(models)
    emp_cf_plan_a_workgroup.associate(models)
    emp_cf_plan_b_function.associate(models)
    emp_cf_plan_c_level.associate(models)
    emp_cf_plan_d_grade.associate(models)
    emp_cf_plan_posttitle.associate(models)
    emp_cf_rec_01_education.associate(models)
    emp_cf_rec_02_fieldstudy.associate(models)
    emp_cf_rec_03_yearexp.associate(models)
    emp_cf_rec_04_age.associate(models)
    emp_cf_rec_05_english.associate(models)
}

module.exports = {CFHRInit, CFHRAssociate}
