const supertest = require('supertest');
const sequelize = require('./setupTests.js');
const app = require('../app.js');
const { material_receive, purchase_order } = require('../constants');

beforeAll(async () => {
  await sequelize.sync({ force: true }); // This will create the tables
});

afterAll(async () => {
  await sequelize.close();
});

beforeEach(async () => {

});

describe('Material Receipt Controller', () => {
  describe.skip('Create Material Receipt first time', () => {
        it('should return 200, Successfully received ordered materials.', async () => {
          const user1 = { email: 'vernon@gmail.com', password: '1234' };
          const user = await supertest(app).post('/api/users/login').send(user1);
          const userToken = user.body.token;
          const user_id = user.body.id_number;

          const addMaterialReceipt = [
            {
                po_no: "PO2408-003",
                item_no: "1",
                stock_code: "CODE006",
                storage: "ST2",
                is_received: false,
                bin: "BL1",
                currency: "IDR",
                trans_type: material_receive,
                qty: 1000,
                rate: 1,
                unit_cost: 1000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 1000000,
                tbl_mat_po: {
                    id: 344,
                    po_no: "PO2408-003",
                    pr_quote_no: "13",
                    branch_code: "ABASET",
                    storage: "ST2",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "123",
                    due_date: "2024-08-18T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 1000000,
                    net_sub_total: 800000,
                    disc_total: 20,
                    disc_total_amount: 200000,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 1000,
                    total_payment: 801000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Adjustment PO",
                    po_status: "Released",
                    po_complete_date: null,
                    requested_date: "2024-08-18T00:00:00.000Z",
                    po_date_created: "2024-08-18T00:00:00.000Z",
                    createdAt: "2024-08-18T05:46:30.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 50,
                doc_ref_no: "PO2408-003",
                doc_no: "MR2408-001",
                item_id: 866,
                reg_by: user_id,
                bin_location: "BL1",
                unit_price: 1000,
                branch: "ABASET",
                amount: 50000,
                qty_in: 50,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-002",
                item_no: "1",
                stock_code: "CODE002",
                storage: "CODE001",
                is_received: false,
                bin: "BL2",
                currency: "IDR",
                trans_type: material_receive,
                qty: 200,
                rate: 1,
                unit_cost: 2000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 400000,
                tbl_mat_po: {
                    id: 343,
                    po_no: "PO2408-002",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "345",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 400000,
                    net_sub_total: 400000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 400000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-06T10:26:43.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-06T09:23:02.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 60,
                doc_ref_no: "PO2408-002",
                doc_no: "MR2408-001",
                item_id: 865,
                reg_by: user_id,
                bin_location: "BL2",
                unit_price: 2000,
                branch: "ABASE",
                amount: 120000,
                qty_in: 60,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-001",
                item_no: "2",
                stock_code: "CODE004",
                storage: "CODE001",
                is_received: false,
                bin: "BIN010",
                currency: "IDR",
                trans_type: material_receive,
                qty: 100,
                rate: 1,
                unit_cost: 1000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 100000,
                tbl_mat_po: {
                    id: 342,
                    po_no: "PO2408-001",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "270468",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 300000,
                    net_sub_total: 300000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 300000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-05T15:49:34.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-05T15:41:38.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 70,
                doc_ref_no: "PO2408-001",
                doc_no: "MR2408-001",
                item_id: 864,
                reg_by: user_id,
                bin_location: "BIN010",
                unit_price: 1000,
                branch: "ABASE",
                amount: 70000,
                qty_in: 70,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-001",
                item_no: "1",
                stock_code: "CODE002",
                storage: "CODE001",
                is_received: false,
                bin: "BL2",
                currency: "IDR",
                trans_type: material_receive,
                qty: 100,
                rate: 1,
                unit_cost: 2000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 200000,
                tbl_mat_po: {
                    id: 342,
                    po_no: "PO2408-001",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "270468",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 300000,
                    net_sub_total: 300000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 300000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-05T15:49:34.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-05T15:41:38.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 80,
                doc_ref_no: "PO2408-001",
                doc_no: "MR2408-001",
                item_id: 863,
                reg_by: user_id,
                bin_location: "BL2",
                unit_price: 2000,
                branch: "ABASE",
                amount: 160000,
                qty_in: 80,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            }
          ]
          
          const response = await supertest(app).post('/api/materialreceives').set('Authorization', `Bearer ${userToken}`).send(addMaterialReceipt);
          expect(response.status).toBe(201);
          expect(response.body.message).toBe('Successfully received ordered materials.');
          stockCodeByBranch(userToken)
          stockCodeByStorage(userToken)
        });
        it('should return 409, Doc Number already exist', async () => {
          const user1 = { email: 'vernon@gmail.com', password: '1234' };
          const user = await supertest(app).post('/api/users/login').send(user1);
          const userToken = user.body.token;
          const user_id = user.body.id_number;

          const addMaterialReceipt = [
            {
                po_no: "PO2408-003",
                item_no: "1",
                stock_code: "CODE006",
                storage: "ST2",
                is_received: false,
                bin: "BL1",
                currency: "IDR",
                trans_type: material_receive,
                qty: 1000,
                rate: 1,
                unit_cost: 1000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 1000000,
                tbl_mat_po: {
                    id: 344,
                    po_no: "PO2408-003",
                    pr_quote_no: "13",
                    branch_code: "ABASET",
                    storage: "ST2",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "123",
                    due_date: "2024-08-18T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 1000000,
                    net_sub_total: 800000,
                    disc_total: 20,
                    disc_total_amount: 200000,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 1000,
                    total_payment: 801000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Adjustment PO",
                    po_status: "Released",
                    po_complete_date: null,
                    requested_date: "2024-08-18T00:00:00.000Z",
                    po_date_created: "2024-08-18T00:00:00.000Z",
                    createdAt: "2024-08-18T05:46:30.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 50,
                doc_ref_no: "PO2408-003",
                doc_no: "MR2408-001",
                item_id: 866,
                reg_by: user_id,
                bin_location: "BL1",
                unit_price: 1000,
                branch: "ABASET",
                amount: 50000,
                qty_in: 50,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-002",
                item_no: "1",
                stock_code: "CODE002",
                storage: "CODE001",
                is_received: false,
                bin: "BL2",
                currency: "IDR",
                trans_type: material_receive,
                qty: 200,
                rate: 1,
                unit_cost: 2000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 400000,
                tbl_mat_po: {
                    id: 343,
                    po_no: "PO2408-002",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "345",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 400000,
                    net_sub_total: 400000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 400000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-06T10:26:43.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-06T09:23:02.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 60,
                doc_ref_no: "PO2408-002",
                doc_no: "MR2408-001",
                item_id: 865,
                reg_by: user_id,
                bin_location: "BL2",
                unit_price: 2000,
                branch: "ABASE",
                amount: 120000,
                qty_in: 60,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-001",
                item_no: "2",
                stock_code: "CODE004",
                storage: "CODE001",
                is_received: false,
                bin: "BIN010",
                currency: "IDR",
                trans_type: material_receive,
                qty: 100,
                rate: 1,
                unit_cost: 1000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 100000,
                tbl_mat_po: {
                    id: 342,
                    po_no: "PO2408-001",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "270468",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 300000,
                    net_sub_total: 300000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 300000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-05T15:49:34.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-05T15:41:38.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 70,
                doc_ref_no: "PO2408-001",
                doc_no: "MR2408-001",
                item_id: 864,
                reg_by: user_id,
                bin_location: "BIN010",
                unit_price: 1000,
                branch: "ABASE",
                amount: 70000,
                qty_in: 70,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-001",
                item_no: "1",
                stock_code: "CODE002",
                storage: "CODE001",
                is_received: false,
                bin: "BL2",
                currency: "IDR",
                trans_type: material_receive,
                qty: 100,
                rate: 1,
                unit_cost: 2000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 200000,
                tbl_mat_po: {
                    id: 342,
                    po_no: "PO2408-001",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "270468",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 300000,
                    net_sub_total: 300000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 300000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-05T15:49:34.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-05T15:41:38.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 80,
                doc_ref_no: "PO2408-001",
                doc_no: "MR2408-001",
                item_id: 863,
                reg_by: user_id,
                bin_location: "BL2",
                unit_price: 2000,
                branch: "ABASE",
                amount: 160000,
                qty_in: 80,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            }
          ]
          
          const response = await supertest(app).post('/api/materialreceives').set('Authorization', `Bearer ${userToken}`).send(addMaterialReceipt);
          expect(response.status).toBe(409);
          expect(response.body.message).toBe('Doc Number already exist');
        });
        it('should return 400, Qty To Receive cannot over than Outstanding. Please refresh the page.', async () => {
          const user1 = { email: 'vernon@gmail.com', password: '1234' };
          const user = await supertest(app).post('/api/users/login').send(user1);
          const userToken = user.body.token;
          const user_id = user.body.id_number;

          const addMaterialReceipt = [
            {
                po_no: "PO2408-003",
                item_no: "1",
                stock_code: "CODE006",
                storage: "ST2",
                is_received: false,
                bin: "BL1",
                currency: "IDR",
                trans_type: material_receive,
                qty: 1000,
                rate: 1,
                unit_cost: 1000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 1000000,
                tbl_mat_po: {
                    id: 344,
                    po_no: "PO2408-003",
                    pr_quote_no: "13",
                    branch_code: "ABASET",
                    storage: "ST2",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "123",
                    due_date: "2024-08-18T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 1000000,
                    net_sub_total: 800000,
                    disc_total: 20,
                    disc_total_amount: 200000,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 1000,
                    total_payment: 801000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Adjustment PO",
                    po_status: "Released",
                    po_complete_date: null,
                    requested_date: "2024-08-18T00:00:00.000Z",
                    po_date_created: "2024-08-18T00:00:00.000Z",
                    createdAt: "2024-08-18T05:46:30.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 50,
                doc_ref_no: "PO2408-003",
                doc_no: "MR2408-001",
                item_id: 866,
                reg_by: user_id,
                bin_location: "BL1",
                unit_price: 1000,
                branch: "ABASET",
                amount: 50000,
                qty_in: 1010,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-002",
                item_no: "1",
                stock_code: "CODE002",
                storage: "CODE001",
                is_received: false,
                bin: "BL2",
                currency: "IDR",
                trans_type: material_receive,
                qty: 200,
                rate: 1,
                unit_cost: 2000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 400000,
                tbl_mat_po: {
                    id: 343,
                    po_no: "PO2408-002",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "345",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 400000,
                    net_sub_total: 400000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 400000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-06T10:26:43.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-06T09:23:02.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 60,
                doc_ref_no: "PO2408-002",
                doc_no: "MR2408-001",
                item_id: 865,
                reg_by: user_id,
                bin_location: "BL2",
                unit_price: 2000,
                branch: "ABASE",
                amount: 120000,
                qty_in: 60,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-001",
                item_no: "2",
                stock_code: "CODE004",
                storage: "CODE001",
                is_received: false,
                bin: "BIN010",
                currency: "IDR",
                trans_type: material_receive,
                qty: 100,
                rate: 1,
                unit_cost: 1000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 100000,
                tbl_mat_po: {
                    id: 342,
                    po_no: "PO2408-001",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "270468",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 300000,
                    net_sub_total: 300000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 300000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-05T15:49:34.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-05T15:41:38.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 70,
                doc_ref_no: "PO2408-001",
                doc_no: "MR2408-001",
                item_id: 864,
                reg_by: user_id,
                bin_location: "BIN010",
                unit_price: 1000,
                branch: "ABASE",
                amount: 70000,
                qty_in: 70,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            },
            {
                po_no: "PO2408-001",
                item_no: "1",
                stock_code: "CODE002",
                storage: "CODE001",
                is_received: false,
                bin: "BL2",
                currency: "IDR",
                trans_type: material_receive,
                qty: 100,
                rate: 1,
                unit_cost: 2000,
                discount: 0,
                disc_amount: 0,
                tax: 0,
                tax_amount: 0,
                total_amount: 200000,
                tbl_mat_po: {
                    id: 342,
                    po_no: "PO2408-001",
                    pr_quote_no: "",
                    branch_code: "ABASE",
                    storage: "CODE001",
                    supplier_id: "supplier2",
                    purchase_instruct: "purchase_instruct",
                    delivery_instruct: "delivery_instruct",
                    created_by: "270468",
                    due_date: "2024-08-06T00:00:00.000Z",
                    term: 0,
                    requestor: "123",
                    trans_type: purchase_order,
                    approved_by: "vernon",
                    approved_date: "2024-08-20T05:44:45.000Z",
                    approved_status: "Approved",
                    sub_total: 300000,
                    net_sub_total: 300000,
                    disc_total: 0,
                    disc_total_amount: 0,
                    tax: 0,
                    tax_amount: 0,
                    freight_code: "CODE009",
                    freight_cost: 0,
                    total_payment: 300000,
                    cost_center: "CC002",
                    contract_no: "contract_no",
                    po_type: "Purchase Order",
                    po_status: "Released",
                    po_complete_date: "2024-08-05T15:49:34.000Z",
                    requested_date: "2024-08-06T00:00:00.000Z",
                    po_date_created: "2024-08-06T00:00:00.000Z",
                    createdAt: "2024-08-05T15:41:38.000Z",
                    updatedAt: "2024-08-20T05:44:45.000Z",
                    supplier_details: {
                        branch_code: "supplier2",
                        com_name: "n.s2"
                    }
                },
                checked: true,
                date: "2024-08-20T05:49:47.586Z",
                qty_in_input: 80,
                doc_ref_no: "PO2408-001",
                doc_no: "MR2408-001",
                item_id: 863,
                reg_by: user_id,
                bin_location: "BL2",
                unit_price: 2000,
                branch: "ABASE",
                amount: 160000,
                qty_in: 80,
                qty_out: 0,
                qty_bal: 0,
                balance: 0,
                supplier_customer: "supplier2",
                is_order: false
            }
          ]
          
          const response = await supertest(app).post('/api/materialreceives').set('Authorization', `Bearer ${userToken}`).send(addMaterialReceipt);
          expect(response.status).toBe(400);
          expect(response.body.message).toBe('Qty To Receive cannot over than Outstanding. Please refresh the page.');
        });
    });

  describe('Create Material Receipt when already have existing stock', () => {
    it('should return 200, Successfully received ordered materials.', async () => {
      const user1 = { email: 'vernon@gmail.com', password: '1234' };
      const user = await supertest(app).post('/api/users/login').send(user1);
      const userToken = user.body.token;
      const user_id = user.body.id_number;

      const addMaterialReceipt = [
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-001",
            item_no: "1",
            branch: "ABASE",
            item_id: 552,
            stock_code: "CODE002",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 100,
            qty_in: 50,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 2000,
            amount: 100000,
            stock_value: 160000,
            cost_price_average: 2000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 342,
                po_no: "PO2408-001",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "270468",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 300000,
                net_sub_total: 300000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 300000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-05T15:41:38.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 50,
            checked: true,
            qty_in_input: 50,
            is_order: false
        },
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-001",
            item_no: "2",
            branch: "ABASE",
            item_id: 551,
            stock_code: "CODE004",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 100,
            qty_in: 40,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 1000,
            amount: 40000,
            stock_value: 40000,
            cost_price_average: 1000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 342,
                po_no: "PO2408-001",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "270468",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 300000,
                net_sub_total: 300000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 300000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-05T15:41:38.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 40,
            checked: true,
            qty_in_input: 40,
            is_order: false
        },
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-002",
            item_no: "1",
            branch: "ABASE",
            item_id: 550,
            stock_code: "CODE002",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 200,
            qty_in: 100,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 2000,
            amount: 200000,
            stock_value: 60000,
            cost_price_average: 2000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 343,
                po_no: "PO2408-002",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "345",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 400000,
                net_sub_total: 400000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 400000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-06T09:23:02.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 30,
            checked: true,
            qty_in_input: 100,
            is_order: false
        },
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-003",
            item_no: "1",
            branch: "ABASET",
            item_id: 549,
            stock_code: "CODE006",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 1000,
            qty_in: 200,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 1000,
            amount: 200000,
            stock_value: 20000,
            cost_price_average: 1000,
            storage: "ST2",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 344,
                po_no: "PO2408-003",
                pr_quote_no: "13",
                branch_code: "ABASET",
                storage: "ST2",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "123",
                due_date: "2024-08-18T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 1000000,
                net_sub_total: 800000,
                disc_total: 20,
                disc_total_amount: 200000,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 1000,
                total_payment: 801000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Adjustment PO",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:24:20.000Z",
                requested_date: "2024-08-18T00:00:00.000Z",
                po_date_created: "2024-08-18T00:00:00.000Z",
                createdAt: "2024-08-18T05:46:30.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 20,
            checked: true,
            qty_in_input: 200,
            is_order: false
        }
      ]
      
      const response = await supertest(app).post('/api/materialreceives').set('Authorization', `Bearer ${userToken}`).send(addMaterialReceipt);
      expect(response.status).toBe(201);
      expect(response.body.message).toBe('Successfully received ordered materials.');
    });
    it.skip('should return 409, Doc Number already exist', async () => {
      const user1 = { email: 'vernon@gmail.com', password: '1234' };
      const user = await supertest(app).post('/api/users/login').send(user1);
      const userToken = user.body.token;
      const user_id = user.body.id_number;

      const addMaterialReceipt = [
        {
            doc_no: "MR2408-001",
            doc_ref_no: "PO2408-001",
            item_no: "1",
            branch: "ABASE",
            item_id: 552,
            stock_code: "CODE002",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 100,
            qty_in: 50,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 2000,
            amount: 100000,
            stock_value: 160000,
            cost_price_average: 2000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 342,
                po_no: "PO2408-001",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "270468",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 300000,
                net_sub_total: 300000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 300000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-05T15:41:38.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 50,
            checked: true,
            qty_in_input: 50,
            is_order: false
        },
        {
            doc_no: "MR2408-001",
            doc_ref_no: "PO2408-001",
            item_no: "2",
            branch: "ABASE",
            item_id: 551,
            stock_code: "CODE004",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 100,
            qty_in: 40,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 1000,
            amount: 40000,
            stock_value: 40000,
            cost_price_average: 1000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 342,
                po_no: "PO2408-001",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "270468",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 300000,
                net_sub_total: 300000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 300000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-05T15:41:38.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 40,
            checked: true,
            qty_in_input: 40,
            is_order: false
        },
        {
            doc_no: "MR2408-001",
            doc_ref_no: "PO2408-002",
            item_no: "1",
            branch: "ABASE",
            item_id: 550,
            stock_code: "CODE002",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 200,
            qty_in: 100,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 2000,
            amount: 200000,
            stock_value: 60000,
            cost_price_average: 2000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 343,
                po_no: "PO2408-002",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "345",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 400000,
                net_sub_total: 400000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 400000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-06T09:23:02.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 30,
            checked: true,
            qty_in_input: 100,
            is_order: false
        },
        {
            doc_no: "MR2408-001",
            doc_ref_no: "PO2408-003",
            item_no: "1",
            branch: "ABASET",
            item_id: 549,
            stock_code: "CODE006",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 1000,
            qty_in: 200,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 1000,
            amount: 200000,
            stock_value: 20000,
            cost_price_average: 1000,
            storage: "ST2",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 344,
                po_no: "PO2408-003",
                pr_quote_no: "13",
                branch_code: "ABASET",
                storage: "ST2",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "123",
                due_date: "2024-08-18T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 1000000,
                net_sub_total: 800000,
                disc_total: 20,
                disc_total_amount: 200000,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 1000,
                total_payment: 801000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Adjustment PO",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:24:20.000Z",
                requested_date: "2024-08-18T00:00:00.000Z",
                po_date_created: "2024-08-18T00:00:00.000Z",
                createdAt: "2024-08-18T05:46:30.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 20,
            checked: true,
            qty_in_input: 200,
            is_order: false
        }
      ]
      
      const response = await supertest(app).post('/api/materialreceives').set('Authorization', `Bearer ${userToken}`).send(addMaterialReceipt);
      expect(response.status).toBe(409);
      expect(response.body.message).toBe('Doc Number already exist');
    });

    it.skip('should return 400, Qty To Receive cannot over than Outstanding. Please refresh the page.', async () => {
      const user1 = { email: 'vernon@gmail.com', password: '1234' };
      const user = await supertest(app).post('/api/users/login').send(user1);
      const userToken = user.body.token;
      const user_id = user.body.id_number;

      const addMaterialReceipt = [
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-001",
            item_no: "1",
            branch: "ABASE",
            item_id: 552,
            stock_code: "CODE002",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 100,
            qty_in: 500,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 2000,
            amount: 100000,
            stock_value: 160000,
            cost_price_average: 2000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 342,
                po_no: "PO2408-001",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "270468",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 300000,
                net_sub_total: 300000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 300000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-05T15:41:38.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 50,
            checked: true,
            qty_in_input: 50,
            is_order: false
        },
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-001",
            item_no: "2",
            branch: "ABASE",
            item_id: 551,
            stock_code: "CODE004",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 100,
            qty_in: 40,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 1000,
            amount: 40000,
            stock_value: 40000,
            cost_price_average: 1000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 342,
                po_no: "PO2408-001",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "270468",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 300000,
                net_sub_total: 300000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 300000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-05T15:41:38.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 40,
            checked: true,
            qty_in_input: 40,
            is_order: false
        },
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-002",
            item_no: "1",
            branch: "ABASE",
            item_id: 550,
            stock_code: "CODE002",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 200,
            qty_in: 100,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 2000,
            amount: 200000,
            stock_value: 60000,
            cost_price_average: 2000,
            storage: "CODE001",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 343,
                po_no: "PO2408-002",
                pr_quote_no: "",
                branch_code: "ABASE",
                storage: "CODE001",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "345",
                due_date: "2024-08-06T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 400000,
                net_sub_total: 400000,
                disc_total: 0,
                disc_total_amount: 0,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 0,
                total_payment: 400000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Purchase Order",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:26:35.000Z",
                requested_date: "2024-08-06T00:00:00.000Z",
                po_date_created: "2024-08-06T00:00:00.000Z",
                createdAt: "2024-08-06T09:23:02.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 30,
            checked: true,
            qty_in_input: 100,
            is_order: false
        },
        {
            doc_no: "MR2408-002",
            doc_ref_no: "PO2408-003",
            item_no: "1",
            branch: "ABASET",
            item_id: 549,
            stock_code: "CODE006",
            trans_type: material_receive,
            supplier_customer: "supplier2",
            qty: 1000,
            qty_in: 200,
            qty_out: 0,
            qty_bal: 0,
            balance: 0,
            currency: "IDR",
            rate: 1,
            unit_price: 1000,
            amount: 200000,
            stock_value: 20000,
            cost_price_average: 1000,
            storage: "ST2",
            reg_by: user_id,
            date: "2024-08-21T02:53:49.439Z",
            supplier_customer_desc: "n.s2",
            tbl_mat_po: {
                id: 344,
                po_no: "PO2408-003",
                pr_quote_no: "13",
                branch_code: "ABASET",
                storage: "ST2",
                supplier_id: "supplier2",
                purchase_instruct: "purchase_instruct",
                delivery_instruct: "delivery_instruct",
                created_by: "123",
                due_date: "2024-08-18T00:00:00.000Z",
                term: 0,
                requestor: "123",
                trans_type: purchase_order,
                approved_by: "vernon",
                approved_date: "2024-08-20T06:02:17.000Z",
                approved_status: "Approved",
                sub_total: 1000000,
                net_sub_total: 800000,
                disc_total: 20,
                disc_total_amount: 200000,
                tax: 0,
                tax_amount: 0,
                freight_code: "CODE009",
                freight_cost: 1000,
                total_payment: 801000,
                cost_center: "CC002",
                contract_no: "contract_no",
                po_type: "Adjustment PO",
                po_status: "Partial Received",
                po_complete_date: "2024-08-20T08:24:20.000Z",
                requested_date: "2024-08-18T00:00:00.000Z",
                po_date_created: "2024-08-18T00:00:00.000Z",
                createdAt: "2024-08-18T05:46:30.000Z",
                updatedAt: "2024-08-21T02:52:54.000Z"
            },
            supplier_customer_details: {
                branch_code: "supplier2",
                com_name: "n.s2"
            },
            qty_in_sum: 20,
            checked: true,
            qty_in_input: 200,
            is_order: false
        }
      ]

      const response = await supertest(app).post('/api/materialreceives').set('Authorization', `Bearer ${userToken}`).send(addMaterialReceipt);
      expect(response.status).toBe(400);
      expect(response.body.message).toBe('Qty To Receive cannot over than Outstanding. Please refresh the page.');
    });
  });

  describe.skip('create Material Receipt with concurrent request from multiple users', () => {
    it('should receive just a request', async () => {
      const user1 = { email: 'user1@gmail.com', password: 'user1' };
      const user2 = { email: 'user2@gmail.com', password: 'user2' };
      const user3 = { email: 'vernon@gmail.com', password: '1234' };

      const user1Login = await supertest(app).post('/api/users/login').send(user1);
      const user2Login = await supertest(app).post('/api/users/login').send(user2);
      const user3Login = await supertest(app).post('/api/users/login').send(user3);

      const user1Token = user1Login.body.token;
      const user2Token = user2Login.body.token;
      const user3Token = user3Login.body.token;

      const createUomRequests = [
        supertest(app)
          .post('/api/materialreceives')
          .set('Authorization', `Bearer ${user1Token}`)
          .send(addMaterialReceipt),

        supertest(app)
          .post('/api/materialreceives')
          .set('Authorization', `Bearer ${user2Token}`)
          .send(addMaterialReceipt),

        supertest(app)
          .post('/api/materialreceives')
          .set('Authorization', `Bearer ${user3Token}`)
          .send(addMaterialReceipt)
      ];

      const responses = await Promise.all(createUomRequests);
      const successfulResponses = responses.filter(response => response.status === 201);
      // For example, expect only one successful creation and the rest to be conflicts
      expect(successfulResponses.length).toBe(1);
    });
  });
});